# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.10. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GoXbuildGo < Formula
  desc ""
  homepage "https://github.com/muquit/go-xbuild-go"
  version "1.0.10"
  license "MIT"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-darwin-arm64.d.tar.gz"
    sha256 "f2afe87c6903e956851b2f7935c2cc0885ce463711aa7546ce56172d5df773e7"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-darwin-amd64.d.tar.gz"
    sha256 "31a49e1995507cfb6ce78b53d025711144d7e14cee19737d7b553312c15e294d"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-linux-amd64.d.tar.gz"
    sha256 "f7c3d9f8697bd0607dea33fe03a9298b955656d30a58e19fa411f4e6532a4224"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-linux-arm64.d.tar.gz"
    sha256 "df920b24356ba05153095cb6079449108fb1161c0029d1a1dfa23ce1cab70a6b"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-darwin-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-darwin-amd64" => "go-xbuild-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-linux-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-linux-amd64" => "go-xbuild-go"
      end
    end
  end
end
