# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.10. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GoXbuildGo < Formula
  desc ""
  homepage "https://github.com/muquit/go-xbuild-go"
  version "1.0.10"
  license "MIT"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-darwin-arm64.d.tar.gz"
    sha256 "66ff7d5fb45bdd224f1333eb4f8cdd65ca4cef2a57af88fcfe10b11dd7187a48"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-darwin-amd64.d.tar.gz"
    sha256 "7c0ed5340af3831ce2a27ed06f3ab37504707a4148a13182c35a799bb4bebbb2"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-linux-amd64.d.tar.gz"
    sha256 "8d1569a47fd7edcd7cf9bc4ba10bb34a1cdee5326b77ca48c7b7240c4c24b7ac"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.10/go-xbuild-go-v1.0.10-linux-arm64.d.tar.gz"
    sha256 "fcf22013156efdbab1d2ad83fb3bf5d4bd51bc39bcb0b7380e81901dc52baeb2"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-darwin-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-darwin-amd64" => "go-xbuild-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-linux-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-linux-amd64" => "go-xbuild-go"
      end
    end
  end
end
