# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.8. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GoXbuildGo < Formula
  desc ""
  homepage "https://github.com/muquit/go-xbuild-go"
  version "1.0.8"
  license "MIT"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.8/go-xbuild-go-v1.0.8-darwin-arm64.d.tar.gz"
    sha256 "5b683ce1574ac8ea22a98432ce7efe1f70165c82c0a264e898ad5943381b4aa8"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.8/go-xbuild-go-v1.0.8-darwin-amd64.d.tar.gz"
    sha256 "cb0a44edc3fec3e17441c4babf76dabb9c07dd94effc4efa7580079a2b67edbc"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.8/go-xbuild-go-v1.0.8-linux-amd64.d.tar.gz"
    sha256 "3b20b6a5d10f20a1d09b80a739a9e96e270c524deebeae150b97dfbf4a03b0b0"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/go-xbuild-go/releases/download/v1.0.8/go-xbuild-go-v1.0.8-linux-arm64.d.tar.gz"
    sha256 "fa597ba38a75344cc5c21901ca274f8c2df4e1856b88ad38cf6e9f04f3c165ed"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-darwin-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-darwin-amd64" => "go-xbuild-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "go-xbuild-go-v#{version}-linux-arm64" => "go-xbuild-go"
      else
        bin.install "go-xbuild-go-v#{version}-linux-amd64" => "go-xbuild-go"
      end
    end
  end
end
